# Generated by Django 5.0.6 on 2024-11-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('tract', models.IntegerField()),
                ('pin', models.CharField(max_length=500)),
                ('structure', models.CharField(max_length=500)),
                ('interest', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('street_address', models.CharField(max_length=500)),
                ('mailing_address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('occupants', models.IntegerField()),
                ('works_land', models.CharField(max_length=500)),
                ('contacted', models.CharField(max_length=500)),
                ('attempts', models.CharField(max_length=500)),
                ('consultation', models.CharField(max_length=500)),
                ('follow_up', models.CharField(max_length=500)),
                ('comments', models.TextField()),
                ('page_no', models.CharField(max_length=500)),
                ('keep_delete', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('commodity', models.CharField(max_length=500)),
                ('pipeline_status', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_records', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRecordCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('tract', models.IntegerField()),
                ('pin', models.CharField(max_length=500)),
                ('structure', models.CharField(max_length=500)),
                ('interest', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('street_address', models.CharField(max_length=500)),
                ('mailing_address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('occupants', models.IntegerField()),
                ('works_land', models.CharField(max_length=500)),
                ('contacted', models.CharField(max_length=500)),
                ('attempts', models.CharField(max_length=500)),
                ('consultation', models.CharField(max_length=500)),
                ('follow_up', models.CharField(max_length=500)),
                ('comments', models.TextField()),
                ('page_no', models.CharField(max_length=500)),
                ('keep_delete', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('commodity', models.CharField(max_length=500)),
                ('pipeline_status', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_project_records', to='project.project')),
            ],
        ),
    ]
